name: Build iOS IPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Setup iOS
      run: |
        cd ios
        pod install
    
    - name: Build iOS (No Codesign)
      run: |
        flutter build ios --release --no-codesign
    
    - name: Create Unsigned IPA (No Certificate Needed)
      run: |
        # Build unsigned app
        flutter build ios --release --no-codesign
        
        # Create unsigned IPA
        mkdir -p build/ios/ipa/Payload
        cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
        cd build/ios/ipa
        zip -r TAD-Service-Unsigned.ipa Payload/
    
    - name: Upload Unsigned IPA
      uses: actions/upload-artifact@v4
      with:
        name: TAD-Service-Unsigned-IPA
        path: build/ios/ipa/TAD-Service-Unsigned.ipa
        retention-days: 30
    
    - name: Upload dSYM
      uses: actions/upload-artifact@v4
      with:
        name: TAD-Service-dSYM
        path: build/ios/ipa/*.dSYM.zip
        retention-days: 30
